### ISSUE TITLE
[KIT-83] In-memory data resources

### ISSUE THREAD

**Issue by dongreenberg** [run-house/runhouse#50]
Eliminate need to .write() a data object to the filesystem before returning from a function, which can be quite expensive - e.g. after I've preprocessed a dataset that's already backed by files in the filesystem, calling .write() is just copying them for no reason, including a costly partition.

Basically, we have the cluster object store, we should use it to avoid fs reads and writes we don't need (and save the user the trouble of knowing they need to .write() before using data remotely). This also saves us the trouble of finding places to write down data when the user doesn't feel like providing a path, or is just working with an anonymous data object (e.g. returning an rh.Table from a preprocessing fn). This will also clean up a sort of API wrinkle where a pinned object is markedly different from a blob (there doesn't need to be a real difference in terms of user intent), and the relationship between data passed to a resource constructor and the written-down data is a little unclear (e.g. if I do `rh.table(my_ray_table, path="real/path/to/existing.parquet")` which data should fetch return?).

Basic API concepts:

`rh.table(my_table)` 

* If we're on a cluster, saves the data into the clusters obj store, setting `system=this_cluster` and `name=f"table_{random_hex}"` (just like we do to generate random run_keys). The rns_address (whether random or user-provided) is the key in the object store.
* Calling `.save` just persists in the RNS that the object lives on that cluster in the object store. If the cluster goes down, the table is obviously gone.
* If we're not on a cluster, this should just store the data in a `_data` field because there's no need for a local object store (nothing can `.get` the object from the local interpreter anyway).

`rh.table(my_table).write()` would actually save the table down (same as present behavior), but return a **new** table object with path set to the fs path. That eliminates the current `._cached_data` ambiguity (multiple sources of truth), because the original object still holds the original data, and the new returned object just points to the fs data. `rh.table(my_table).write(path="local/path.parquet")` is clearer than the present constructor accepting both (we should probably throw an error if both are passed in, because it's ambiguous). One gotcha: if the user sets the name for the in-memory table and then writes it, should the new table have the same name? If they .save it, should we delete the existing object out of the object store so it's clear that there's only one table with that rns_address (and its not really accessible anymore)? In general, if a user loads an object from_name, the one stored in RNS should be the source of truth, even if there's a local one in the object store.

`my_table.fetch()` and `my_table.stream()` from elsewhere should still work, but now via RPCs - the cluster's .get should already work for fetch, but we'd likely need a new one for stream. For fetch, the object needs to be **pickleable** (not cloudpickle-able) for us to be able to send it over the wire without dealing with python version mismatches (I don't think this is unreasonable).

We need a way to tell for a given blob or table if we need to use the RPCs instead of the existing fs-based operations, and I'm leaning toward actually breaking out the folder-backed table or blob to be separate classes from the in-memory ones. It would probably make the most sense if the in-memory Blob/Table/KVstore etc. classes were actually the base classes, and the folder-backed ones were subclasses. There are a number of advantages to doing this:

* The rpc-based fetch/stream etc. logic is in its own class, not a bunch of branching within the blob/table methods (where we need to store some private state that this object is in the obj-store anyway).
* The in-memory blob/table doesn't need a `path` field.
* There's a clear separation between the folder-backed and infra-backed table types. It makes more sense to me to have an obj-store backed Table base class from which the folder-backed, Postgres-backed, BQ-backed, etc. tables each derive (rather than have BQ be a subclass of the folder-backed table, which is a bit strange).
* Right now we decide on the table type the moment the user passes data into the constructor, which I'm not sure is necessary. If a user passes in a pandas table and simply intends to fetch or  stream it from somewhere else, the logic to do that would be identical to cudf, hf, etc. We mostly branch into separate subclasses for the current tables to handle filesystem logic (write, save, stream, etc.)
* We could instantly add useful KVStore, Pubsub (naming pending), and maybe vectorstore base classes without having to do any integrations - just dead simple python object implementations. We could even support .write() with pickle initially before we pick a proper system to back them.

`rh.blob(my_model)` saves into the object store with key `blob.name` or`f"blob_{randomhex}"`. `rh.blob(my_model, name="my_model")` and `rh.Blob.from_name("my_model")` should behave identically to `rh.pin_to_memory("my_model", my_model)` and `rh.get_pinned_object("my_model")` , (except with rns_address as the obj_store key instead of name, but that's an implementation detail) and ideally replace it. The current pinning system isn't very elegant and eats too much user brainspace.

An immediate implication of the above (because we use pinning for storing results when a user calls `fn.remote`), is that `fn.remote` can just wrap the result in a `blob` before returning instead of returning the run_key. Wrapping a result in rh.blob is common enough that it makes sense for `.remote` to mean "please return a remote object." The current `.remote` behavior of returning the run_key is actually "run this async and return a key to retrieve the result", which I think would make more sense to be called `fn.async`  or `fn.submit`, considering the fact that most users don't seem to know we support async because the naming is unclear (submit could make it clearer that the function will continue to run in the background even if they kill the interpreter locally). Also, right now we need to INFO log a bunch of instructions for killing or retrieving for every `.remote` call, but this isn't necessary and looks ugly when the user just wants a remote object back.

Lastly, supporting remote in-memory objects opens the door to remote calls on those objects. We could pretty easily support this just by intercepting any call on the object, and if the rh.blob doesn't have that function/attr, we try RPCing the call over to the cluster. Like this:

```
class Blob(Resource):
    ...
    def __getattribute__(self,name):
        if not_a_blob_attr(name):
            remote_attr = self.get_attr_over_rpc(name)
            if name == "__call__" or hasattr(remote_attr, "__call__"):
                def newfunc(*args, **kwargs):
                    result = self.call_on_obj_via_rpc(name, *args, **kwargs)
                    return result if self.is_primitive(result) else rh.blob(result)
                return newfunc
            else:
                return remote_attr
        else:
            return attr
```

This would make our remote objects real remote objects, and save a lot of trouble creating one-off functions to send to the cluster to call methods on objects. You can do something crazy like:

```
model = rh.blob(my_model).to(gpu).cuda()        # But can't use .to("cuda") because it'd call blob's .to
local_pil_image = model("my_input_string").fetch()
```

So overall the benefits of this change are:

1. Saving mental and performance overhead of unneeded .write calls
2. More coherent relationship between python table/blob object and folder-backed, less error prone with multiple sources of truth
3. Saving mental overhead of separate pinning APIs
4. Clearer and lower mental overhead .remote APIs
5. Powerful native remote object support

<sub>From [SyncLinear.com](https://synclinear.com) | [KIT-83](https://linear.app/runhouse/issue/KIT-83/in-memory-data-resources)</sub>

**Comment by jlewitt1** [comment]
_“Calling .save just persists in the RNS that the object lives on that cluster in the object store. If the cluster goes down, the table is obviously gone.”_

- I think there’s an open question of how to handle resources on the RNS side if the underlying data on the cluster no longer exists or the cluster is terminated - should we be deleting it from the RNS automatically or keep the metadata up for the user to view and have them delete manually / replace the path to the underlying resource to a new cluster / file system if they want the data to live somewhere else?

_“If we’re not on a cluster, this should just store the data in a _data field because there’s no need for a local object store (nothing can .get the object from the local interpreter anyway).”_

- Do you mean that if the data is not a cluster we would access it via something like .fetch() or pickle.loads(my_table.data) , and if it is on a cluster we would first do a .get() to fetch the key from the cluster’s object store and then access the underlying data via an RPC (instead of fs based operations)?

_“We need a way to tell for a given blob or table if we need to use the RPCs instead of the existing fs-based operations, and I’m leaning toward actually breaking out the folder-backed table or blob to be separate classes from the in-memory ones”_

- Are you implying we need a way to determine whether to use an RPC to get the data (i.e. it lives on the cluster), vs. using fs operations if it lives on any other system? Why is this different than what we have now by denoting the data's home with the “system” attribute?

**Comment by carolineechen** [comment]
Overall the motivation makes sense to me, for supporting in-memory data resources (no need for an explicit path or saving data down when it already exists in an object on the cluster) and having native remote object support (separate from async). A couple of comments/questions
> In general, if a user loads an object from_name, the one stored in RNS should be the source of truth, even if there's a local one in the object store.

I actually think it makes more sense to have local obj store take precedent over RNS if loading from the cluster that it exists on, as it has the smaller scope. It's probably more likely if they create an object on the cluster to want to access that object rather than a previously set global one (or if they want to access the global one, then they should know and not name the local one the same).

> One gotcha: if the user sets the name for the in-memory table and then writes it, should the new table have the same name?

I think this is something we need to think through some more, with resource naming and handling potentially multiple objects pointing to the same data (and being created from each other) -- maybe some form of versioning or additional metadata to differentiate them? 

> KVStore, Pubsub (naming pending), and maybe vectorstore base classes

Could you expand on this a bit, the motive/how it fits in?

As for @jlewitt1's comment
> I think there’s an open question of how to handle resources on the RNS side if the underlying data on the cluster no longer exists or the cluster is terminated

For this, I think it makes sense to leave the metadata up for the user to reference, and they can manually delete/update it depending on their application. Leaving it up can be helpful if there's metadata that can help users trace back information about the data, why/how/when it was created, etc
