### ISSUE TITLE
[Doc] Issues with Inline Markup Rendering

### ISSUE THREAD

**Issue by langong347** [run-house/runhouse#64]
This is a follow-up to a separate offline discussion about API feedback.

## Describe the Issues
- [x] Since the typos were fixed in this [commit](https://github.com/run-house/runhouse/commit/51281f94a71a26acb0dbb62082d9e8ba7bda5267) by @carolineechen , there is no need to submit a fix-up on my end.

- [x] The open issues are with the rendering of certain inline markups on Runhouse website (v. latest), for example:

- Docstrings under [Package Factory Method](https://runhouse-docs.readthedocs-hosted.com/en/latest/rh_primitives/package.html#package-factory-method), [Blob Factory Method](https://runhouse-docs.readthedocs-hosted.com/en/latest/rh_primitives/blob.html#blob-factory-method):

    <img width="1052" alt="Screenshot 2023-05-13 at 10 22 45 PM" src="https://github.com/run-house/runhouse/assets/23155714/70fa25fa-cc34-4226-b120-970d5b19718f">

- Page [Secrets in Vault](https://runhouse-docs.readthedocs-hosted.com/en/latest/secrets/vault_secrets.html#saving-secrets)

    <img width="1203" alt="Screenshot 2023-05-13 at 10 05 26 PM" src="https://github.com/run-house/runhouse/assets/23155714/48ed2766-ae7d-4918-afa4-ee0d96aba2cb">

## What I've Tried

- The rendering is correct on the local build.

- I also ruled out any conflicting or overriding configurations in the files below:
  - `docs/conf.py` for any conflicting sphinx extension or html theme
  - `.readthedocs.yaml` under project root for any configuration overrides

- I was not able to cross reference doc built from the main branch which was "404 not found" at the time of submitting this issue.

## Next Step

See if those issues will persist the next time we build the remote doc.

**Comment by carolineechen** [comment]
Hi @langong347, thanks for looking into this and sending us the typos and rendering issues! I think these should all be fixed on the [main branch of the docs](https://runhouse-docs.readthedocs-hosted.com/en/main/index.html): [Package](https://runhouse-docs.readthedocs-hosted.com/en/main/api/package.html), [Blob](https://runhouse-docs.readthedocs-hosted.com/en/main/api/blob.html), [Secrets](https://runhouse-docs.readthedocs-hosted.com/en/main/tutorials/secrets_management.html) (the url isn't 1-to-1 with just changing latest to main since I did some sidebar reorganization). Feel free to let us know or create a PR if you spot anything else 😄

**Comment by langong347** [comment]
Thanks @carolineechen  for the pointers! Everything looks normal on the main build.
